database:
  type: "sqlite"
  mysql:
    address: ""
    database: ""
    username: ""
    password: ""
  sqlite:
    file: "database.db"

redis:
  host: ""
  port: 6379
  password: ""

initial-time:
  MENSAL: -1

reset-time:
  MENSAL: -1

discord-webhook-link: ""
webhook-title: "SAINT LIGA - %player% <a:1Espada:1149729957434634403>"
webhook-description: "O jogador %player% foi alterado em %points% e agora possui %total% pontos!"
webhook-footer: "Que a vitória seja dos mais fortes! Rede Saint"
webhook-footer-image: ""
webhook-color: "16711680"

view:
  defaultEventHead: "/texture/6d0f4061bfb767a7f922a6ca7176f7a9b20709bd0512696beb15ea6fa98ca55c"
  filterColor: "&b"
  clanRankingInfo: " &f%time%: &e%pontos% pontos &6(#%position%)"
  mainInventoryName: "Saint Ligas"
  ranking:
    itemName: "&a%player% &6(#%position%)"
    lore:
      - '&fRank: &e%rank%'
  leagueRank:
    material: "/texture/e34a592a79397a8df3997c43091694fc2fb76c883a76cce89f0227e5c9f1dfe"
    name: "&aRanking da liga"
    lore:
      - '&7Veja quais players estão liderando'
      - '&7a liga atualmente'
      - ''
      - '&aClique para ver o ranking da liga!'
  leagueHistoric:
    material: "/texture/ab527a18dec3d6dac532f5555b9119c31b7a8397b8a06d249d0eb39241c5485f"
    name: "&aHistórico de Eventos"
    lore:
      - '&7Veja os eventos anteriores que'
      - '&7você participou'
      - ''
      - '&aClique para ver o histórico!'
  profile:
    name: "&aSeu Perfil"
    lore:
      - '&fSeus rank: &e%rank%'
      - '&fSeus pontos: &e%pontos%'
      - ''
      - '&aClique para ver os eventos que participou!'
  historic:
    name: "&a%event% &8(#%id%)"
    lore:
      - '&fData: &e%data%'
      - '&fPontos: &e%pontos%'
  sortRanking:
    material: "HOPPER"
    name: "&6Filtrar eventos"
    lore:
      - '&7Selecione o evento que deseja ver'
      - ''
      - '%info%'
      - ''
      - '&aClique para mudar o evento.'

remove-group-command: "lp user %player% parent remove %group%"
add-group-command: "lp user %player% parent add %group%"

ranks:
  1:
    display_name: "&7Prata I"
    prefix: "&7[&fPrata I&7]"
    points_needed: 0
    group: 'pratai'
    commands: []
  2:
    display_name: "&7Prata II"
    prefix: "&7[&fPrata II&7]"
    points_needed: 10
    group: 'prataii'
    commands:
      - 'give %player% diamond 1'
  3:
    display_name: "&7Prata III"
    prefix: "&7[&fPrata III&7]"
    points_needed: 20
    group: 'prataiii'
    commands:
      - 'give %player% diamond 2'

# Sistema para premiar mensalmente o top player (1º, 2º e 3º)
auto-reward:
  # Placeholders: %player%
  1:
    - 'money give %player% 1'
  2:
    - 'money give %player% 1'
  3:
    - 'money give $player 1'

reward-per-event:
  Vote:
    name: "Votar"
    points: 1
  DragonSlayer:
    name: "Dragon Slayer"
    points: 15
  TitansBattle:
    gladiador:
      name: "Gladiador"
      points: 15
    killer:
      name: "Killer"
      points: 10
  yEvents:
    BOLAO:
      name: "Bolão"
      points: 3
    CORRIDA:
      name: "Corrida"
      points: 3
    FASTCLICK:
      name: "FastClick"
      points: 3
    FIGHT:
      name: "Fight"
      points: 3
    KILLER:
      name: "Killer"
      points: 3
    LABIRINTO:
      name: "Labirinto"
      points: 3
    LOTERIA:
      name: "Loteria"
      points: 3
    MATEMATICA:
      name: "Matemática"
      points: 3
    PAINTBALL:
      name: "Paintball"
      points: 3
    PALAVRA:
      name: "Palavra"
      points: 3
    PARKOUR:
      name: "Parkour"
      points: 3
    QUIZ:
      name: "Quiz"
      points: 3
    SPLEEF:
      name: "Spleef"
      points: 3
    SUMO:
      name: "Sumo"
      points: 3
    RESTAUM:
      name: "RestaUm"
      points: 3
    FASTCRAFT:
      name: "FastCraft"
      points: 3


top-locations: []